import { GeistSans } from "geist/font/sans";

import { Toaster } from "@henry/ui/sonner";
import { TooltipProvider } from "@henry/ui/tooltip";

import QueryContext from "~/components/context/queryContext";
import SessionContextLayer from "~/components/context/sessionContext";

import "./globals.css";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <SessionContextLayer>
        <QueryContext>
          <TooltipProvider>
            <body className="flex min-h-screen flex-col">{children}</body>
            <Toaster />
          </TooltipProvider>
        </QueryContext>
      </SessionContextLayer>
    </html>
  );
}
