import { GeistSans } from "geist/font/sans";

import { Toaster } from "@henry/ui/sonner";
import { TooltipProvider } from "@henry/ui/tooltip";

import SessionContextLayer from "~/components/sessionContext";

import "./globals.css";

import { ThemeProvider, ThemeToggle } from "@henry/ui/theme";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex min-h-screen flex-col">
        <SessionContextLayer>
          <TRPCReactProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              <TooltipProvider>
                {children}
                <Toaster />
                <div className="absolute bottom-4 right-4">
                  <ThemeToggle />
                </div>
              </TooltipProvider>
            </ThemeProvider>
          </TRPCReactProvider>
        </SessionContextLayer>
      </body>
    </html>
  );
}
